---
#- name: Habilitar NETCONF
#    connection: network_cli
#    junos_netconf:
#    when: ansible_network_os == 'junos'

- name: Enviar template v4
  junos_scp:
    src: ./templates/bogons-v4.j2
    dest: /tmp/
  register: uploadBogonv4

- name: Enviar template v6
  junos_scp: 
    src: ./templates/bogons-v6.j2
    dest: /tmp/
  register: uploadBogonv6

- name: Prefix-List BOGONS
  junos_config:
    lines:
      - load set bogons-v4.j2
      - load set bogons-v6.j2
    comment: "Prefix-list BOGON para IPv4 and IPv6"
  when: uploadBogonv4.changed and uploadBogonv6.changed
  register: loadSetBogons

# Filtro de proteção porta 25, bogons
- name: Criar filtro de firewall
  junos_config: 
    lines:
      - set firewall family inet filter FILTRO-v4
      - edit firewall family inet filter FILTRO-v4
      - set term 1 from address 0.0.0.0/0 
      - set term 1 from protocol tcp
      - set term 1 from port smtp
      - set term 1 then discard
      - set term 2 from source-prefix-list FILTRO-BOGONS-v4
      - set term 2 then discard
      - set term Default then accept
      - top set firewall family inet6 filter FILTRO-v6
      - edit firewall family inet6 filter FILTRO-v6
      - set term 1 from address ::/0
      - set term 1 from next-header tcp
      - set term 1 from port smtp
      - set term 1 then discard
      - set term 2 from source-prefix-list FILTRO-BOGONS-v6-DENY
      - set term 2 then discard
      - set term 3 from source-prefix-list LISTA-BOGONS-v6-ACCEPT
      - set term 3 then accept
      - set term Default then discard
  when: loadSetBogons.changed
  register: criaFiltroFirewall

- name: Incluir filtro de firewall na interface
  junos_config:
    lines:
      - edit interfaces "{{ Interfacev4 }}" unit "{{ Unitv4 }}"
      - set family inet filter input FILTRO-v4
      - set family inet rpf-check
      - top edit interfaces "{{ Interfacev6 }}" unit "{{ Unitv6 }}"
      - set family inet6 filter input FILTRO-v6
      - set family inet6 rpf-check  
  when: criaFiltroFirewall.changed
  register: interfaceFirewall

- name: Check configuração
  junos_config:
    check_commit: yes
  when: interfaceFirewall.changed
  register: commitCheck
 
- name: Confirma o commit
  junos_config:
    confirm_commit: yes
  when: commitCheck.changed

- name: Rollback das configurações
  junos_config:
    rollback: 0
  when: interfaceFirewall.changed == False

