---
- name: Check if the prefix-list v4 already exists
  junos_command:
    commands: show configuration policy-options
    wait_for: result[0] contains FILTRO-BOGONS-v4
    retries: 2
  ignore_errors: yes
  register: checkFiltroBogonsv4

- name: Check if prefix-list v6 accept already exists
  junos_command:
    commands: show configuration policy-options
    wait_for: result[0] contains FILTRO-BOGONS-v6-ACCEPT
    retries: 2
  ignore_errors: yes
  register: checkFiltroBogonsv6Accept

- name: Check if prefix-list v6 deny already exists
  junos_command:  
    commands: show configuration policy-options  
    wait_for: result[0] contains FILTRO-BOGONS-v6-DENY
    retries: 2
  ignore_errors: yes
  register: checkFiltroBogonsv6Deny

- name: Include task scp 
  include_tasks: scp.yaml
 
- name: Create prefix-list BOGONS v4
  junos_config:
    src: bogons-v4.j2
    src_format: set
  when: uploadBogonv4.changed
  register: setBogonV4
 
- name: Create prefix-list BOGONS v6
  junos_config:
    src: bogons-v6.j2
    src_format: set
  when: uploadBogonv6.changed
  register: setBogonV6

# Filtro de proteção porta 25, bogons
- name: Create firewall filter v4
  junos_config: 
    lines:
      - set firewall family inet filter FILTRO-v4 term 1 from address 0.0.0.0/0 
      - set firewall family inet filter FILTRO-v4 term 1 from protocol tcp
      - set firewall family inet filter FILTRO-v4 term 1 from port smtp
      - set firewall family inet filter FILTRO-v4 term 1 then discard
      - set firewall family inet filter FILTRO-v4 term 2 from source-prefix-list FILTRO-BOGONS-v4
      - set firewall family inet filter FILTRO-v4 term 2 then discard
      - set firewall family inet filter FILTRO-v4 term Default then accept
  when: setBogonV4 is succeeded and setBogonV4 is changed
  register: criaFiltroFirewallv4

- name: Create firewall filter v6
  junos_config: 
    lines:
      - set firewall family inet6 filter FILTRO-v6 term 1 from address ::/0
      - set firewall family inet6 filter FILTRO-v6 term 1 from next-header tcp
      - set firewall family inet6 filter FILTRO-v6 term 1 from port smtp
      - set firewall family inet6 filter FILTRO-v6 term 1 then discard
      - set firewall family inet6 filter FILTRO-v6 term 2 from source-prefix-list FILTRO-BOGONS-v6-DENY
      - set firewall family inet6 filter FILTRO-v6 term 2 then discard
      - set firewall family inet6 filter FILTRO-v6 term 3 from source-prefix-list FILTRO-BOGONS-v6-ACCEPT
      - set firewall family inet6 filter FILTRO-v6 term 3 then accept
      - set firewall family inet6 filter FILTRO-v6 term Default then discard
  when: setBogonV6 is succeeded and setBogonV6 is changed
  register: criaFiltroFirewallv6

# Criar task de idempotencia se já existe na interface essas configs - testar flag de interface defined
- name: Include firewall filter in interface
  junos_config:
    lines:
      - set interfaces "{{ Interfacev4 }}" unit "{{ Unitv4 }}" family inet filter input FILTRO-v4
      - set interfaces "{{ Interfacev4 }}" unit "{{ Unitv4 }}" family inet rpf-check
      - set interfaces "{{ Interfacev6 }}" unit "{{ Unitv6 }}" family inet6 filter input FILTRO-v6
      - set interfaces "{{ Interfacev6 }}" unit "{{ Unitv6 }}" family inet6 rpf-check  
  when: criaFiltroFirewallv4 and criaFiltroFirewallv6 is changed and Interfacev4 is defined and Interfacev6 is defined
  register: interfaceFirewall

- name: Rollback
  junos_config:
    rollback: 0
  when: interfaceFirewall is failed
