---
- name: Checa se a prefix-list já existe
  junos_command:
    provider: "{{ connection_info }}"
    commands: show configuration policy-options | match FILTRO-BOGOS-v4
    #wait_for: result[0] contains FILTRO-BOGOS-v4

- name: Enviar template v4
  junos_scp:
    provider: "{{ connection_info }}"
    src: roles/cpe/templates/bogons-v4.j2
    dest: /tmp/
  register: uploadBogonv4

- name: Enviar template v6
  junos_scp: 
    provider: "{{ connection_info }}"
    src: roles/cpe/templates/bogons-v6.j2
    dest: /tmp/
  register: uploadBogonv6

- name: Criar prefix-list BOGONS v4
  junos_config:
    src: bogons-v4.j2
    src_format: set
  when: uploadBogonv4.changed
  register: setBogonV4

- name: Criar prefix-list BOGONS v6
  junos_config:
    src: bogons-v6.j2
    src_format: set
  when: uploadBogonv6.changed
  register: setBogonV6

# Filtro de proteção porta 25, bogons
- name: Criar filtro de firewall v4
  junos_config: 
    provider: "{{ connection_info }}"
    lines:
      - set firewall family inet filter FILTRO-v4 term 1 from address 0.0.0.0/0 
      - set firewall family inet filter FILTRO-v4 term 1 from protocol tcp
      - set firewall family inet filter FILTRO-v4 term 1 from port smtp
      - set firewall family inet filter FILTRO-v4 term 1 then discard
      - set firewall family inet filter FILTRO-v4 term 2 from source-prefix-list FILTRO-BOGONS-v4
      - set firewall family inet filter FILTRO-v4 term 2 then discard
      - set firewall family inet filter FILTRO-v4 term Default then accept
  when: setBogonV4 is succeeded
  register: criaFiltroFirewallv4

- name: Criar filtro de firewall v6
  junos_config: 
    provider: "{{ connection_info }}"
    lines:
      - set firewall family inet6 filter FILTRO-v6 term 1 from address ::/0
      - set firewall family inet6 filter FILTRO-v6 term 1 from next-header tcp
      - set firewall family inet6 filter FILTRO-v6 term 1 from port smtp
      - set firewall family inet6 filter FILTRO-v6 term 1 then discard
      - set firewall family inet6 filter FILTRO-v6 term 2 from source-prefix-list FILTRO-BOGONS-v6-DENY
      - set firewall family inet6 filter FILTRO-v6 term 2 then discard
      - set firewall family inet6 filter FILTRO-v6 term 3 from source-prefix-list FILTRO-BOGONS-v6-ACCEPT
      - set firewall family inet6 filter FILTRO-v6 term 3 then accept
      - set firewall family inet6 filter FILTRO-v6 term Default then discard
  when: setBogonV6 is succeeded
  register: criaFiltroFirewallv6

- name: Incluir filtro de firewall na interface
  junos_config:
    provider: "{{ connection_info }}"
    lines:
      - set interfaces "{{ Interfacev4 }}" unit "{{ Unitv4 }}" family inet filter input FILTRO-v4
      - set interfaces "{{ Interfacev4 }}" unit "{{ Unitv4 }}" family inet rpf-check
      - set interfaces "{{ Interfacev6 }}" unit "{{ Unitv6 }}" family inet6 filter input FILTRO-v6
      - set interfaces "{{ Interfacev6 }}" unit "{{ Unitv6 }}" family inet6 rpf-check  
  when: criaFiltroFirewallv4 and criaFiltroFirewallv6 is changed
  register: interfaceFirewall

- name: Check configuração
  junos_config:
    provider: "{{ connection_info }}"
    check_commit: yes
  when: interfaceFirewall.changed
  register: commitCheck
 
- name: Confirma o commit
  junos_config:
    provider: "{{ connection_info }}"
    confirm_commit: yes
  when: commitCheck.changed

  #- name: Rollback das configurações
  #junos_config:
  #  provider: "{{ connection_info }}"      
  #  rollback: 0
  #when: interfaceFirewall.failed == True
