---
- name: Checa se a prefix-list já existe
  junos_command:
    provider: "{{ connection_info }}"
    commands: show configuration policy-options | match FILTRO-BOGOS-v4
    #wait_for: result[0] contains FILTRO-BOGOS-v4

- name: Prefix-List BOGONS
  junos_config:
    provider: "{{ connection_info }}"
    lines:
      - set policy-options prefix-list FILTRO-BOGONS-v4 0.0.0.0/8
      - set policy-options prefix-list FILTRO-BOGONS-v4 10.0.0.0/8
      - set policy-options prefix-list FILTRO-BOGONS-v4 100.64.0.0/10
      - set policy-options prefix-list FILTRO-BOGONS-v4 127.0.0.0/8
      - set policy-options prefix-list FILTRO-BOGONS-v4 169.254.0.0/16
      - set policy-options prefix-list FILTRO-BOGONS-v4 172.16.0.0/12
      - set policy-options prefix-list FILTRO-BOGONS-v4 192.0.0.0/24
      - set policy-options prefix-list FILTRO-BOGONS-v4 192.168.0.0/16
      - set policy-options prefix-list FILTRO-BOGONS-v4 192.168.0.0/16
      - set policy-options prefix-list FILTRO-BOGONS-v4 198.18.0.0/15
      - set policy-options prefix-list FILTRO-BOGONS-v4 198.51.100.0/24
      - set policy-options prefix-list FILTRO-BOGONS-v4 203.0.113.0/24
      - set policy-options prefix-list FILTRO-BOGONS-v4 224.0.0.0/3
      - set policy-options prefix-list FILTRO-BOGONS-v6-DENY 2001:db8::/32
      - set policy-options prefix-list FILTRO-BOGONS-v6-ACCEPT 2000::/3
      - set policy-options prefix-list FILTRO-BOGONS-v6-ACCEPT 2000::/3
      - set policy-options prefix-list FILTRO-BOGONS-v6-ACCEPT ::/128
      - set policy-options prefix-list FILTRO-BOGONS-v6-ACCEPT ::/128
    comment: "Prefix-list BOGON para IPv4 and IPv6"
  register: setBogons

# Filtro de proteção porta 25, bogons
- name: Criar filtro de firewall
  junos_config: 
    provider: "{{ connection_info }}"
    lines:
      - set firewall family inet filter FILTRO-v4 term 1 from address 0.0.0.0/0 
      - set firewall family inet filter FILTRO-v4 term 1 from protocol tcp
      - set firewall family inet filter FILTRO-v4 term 1 from port smtp
      - set firewall family inet filter FILTRO-v4 term 1 then discard
      - set firewall family inet filter FILTRO-v4 term 2 from source-prefix-list FILTRO-BOGONS-v4
      - set firewall family inet filter FILTRO-v4 term 2 then discard
      - set firewall family inet filter FILTRO-v4 term Default then accept
      - set firewall family inet6 filter FILTRO-v6 term 1 from address ::/0
      - set firewall family inet6 filter FILTRO-v6 term 1 from next-header tcp
      - set firewall family inet6 filter FILTRO-v6 term 1 from port smtp
      - set firewall family inet6 filter FILTRO-v6 term 1 then discard
      - set firewall family inet6 filter FILTRO-v6 term 2 from source-prefix-list FILTRO-BOGONS-v6-DENY
      - set firewall family inet6 filter FILTRO-v6 term 2 then discard
      - set firewall family inet6 filter FILTRO-v6 term 3 from source-prefix-list FILTRO-BOGONS-v6-ACCEPT
      - set firewall family inet6 filter FILTRO-v6 term 3 then accept
      - set firewall family inet6 filter FILTRO-v6 term Default then discard
  when: setBogons.changed
  register: criaFiltroFirewall

- name: Incluir filtro de firewall na interface
  junos_config:
    provider: "{{ connection_info }}"
    lines:
      - set interfaces "{{ Interfacev4 }}" unit "{{ Unitv4 }}" family inet filter input FILTRO-v4
      - set interfaces "{{ Interfacev4 }}" unit "{{ Unitv4 }}" family inet rpf-check
      - set interfaces "{{ Interfacev6 }}" unit "{{ Unitv6 }}" family inet6 filter input FILTRO-v6
      - set interfaces "{{ Interfacev6 }}" unit "{{ Unitv6 }}" family inet6 rpf-check  
  when: criaFiltroFirewall.changed
  register: interfaceFirewall

- name: Check configuração
  junos_config:
    provider: "{{ connection_info }}"
    check_commit: yes
  when: interfaceFirewall.changed
  register: commitCheck
 
- name: Confirma o commit
  junos_config:
    provider: "{{ connection_info }}"
    confirm_commit: yes
  when: commitCheck.changed

  #- name: Rollback das configurações
  #junos_config:
  #  provider: "{{ connection_info }}"      
  #  rollback: 0
  #when: interfaceFirewall.failed == True
