---
- name: Send template v4
  junos_scp:
    provider: "{{ connection_info }}"
    src: roles/cpe/templates/bogons-v4.j2
    dest: /tmp/
  connection: local
  when: checkFiltroBogonsv4 is failed
  register: uploadBogonv4

- name: Send template v6
  junos_scp:
    provider: "{{ connection_info }}"
    src: roles/cpe/templates/bogons-v6.j2
    dest: /tmp/
  connection: local
  when: checkFiltroBogonsv6Accept and checkFiltroBogonsv6Deny is failed
  register: uploadBogonv6
