---
- name: Verificar se a access-list de Filtro v4 existe
  routeros_command:
    commands:
      - /ip firewall address-list print
    wait_for: result[0] contains FILTRO-BOGONS-V4
  ignore_errors: yes
  register: checkFiltroBogonsv4

- name: Verificar se a access-list de Filtro v6 existe
  routeros_command:
    commands:
    - /ipv6 firewall address-list print 
    wait_for: result[0] contains FILTRO-BOGONS-V6
  ignore_errors: yes
  register: checkFiltroBogonsv6

- name: Criar access list BOGONS v4
  routeros_command:
    commands:
    - /ip firewall address-list add address=10.0.0.0/8 list=FILTRO-BOGONS-V4
    - /ip firewall address-list add address=100.64.0.0/10 list=FILTRO-BOGONS-V4
    - /ip firewall address-list add address=127.0.0.0/8 list=FILTRO-BOGONS-V4
    - /ip firewall address-list add address=169.254.0.0/16 list=FILTRO-BOGONS-V4
    - /ip firewall address-list add address=172.16.0.0/12 list=FILTRO-BOGONS-V4
    - /ip firewall address-list add address=192.0.0.0/24 list=FILTRO-BOGONS-V4
    - /ip firewall address-list add address=192.0.2.0/24 list=FILTRO-BOGONS-V4
    - /ip firewall address-list add address=192.168.0.0/24 list=FILTRO-BOGONS-V4
    - /ip firewall address-list add address=198.18.0.0/15 list=FILTRO-BOGONS-V4
    - /ip firewall address-list add address=198.51.100.0/24 list=FILTRO-BOGONS-V4
    - /ip firewall address-list add address=203.0.113.0/24 list=FILTRO-BOGONS-V4
    - /ip firewall address-list add address=224.0.0.0/3 list=FILTRO-BOGONS-V4
  when: checkFiltroBogonsv4 is failed
  register: filtroBogonsv4

- name: Criar access list BOGONS v6
  routeros_command:
    commands:
    - /ipv6 firewall address-list add address=2000::/3 list=FILTRO-BOGONS-V6
    - /ipv6 firewall address-list add address=fe80::/64 list=FILTRO-BOGONS-V6
    - /ipv6 firewall address-list add address=::/128 list=FILTRO-BOGONS-V6
  when: checkFiltroBogonsv6 is failed
  register: filtroBogonsv6

- name: Verificar se filtro SMTP v4 existe
  routeros_command:
    commands:
    - /ip firewall filter print
    wait_for: result[0] contains dst-port=25
  ignore_errors: yes
  register: checkSmtpV4
  
- name: Verificar se filtro SMTP v6 existe
  routeros_command:
    commands:
    - /ipv6 firewall filter print
    wait_for: result[0] contains dst-port=25
  ignore_errors: yes
  register: checkSmtpV6

- name: Configurar bloqueio SMTP v4
  routeros_command:
    commands:
    - /ip firewall filter add chain=forward action=drop src-address=0.0.0.0/0 dst-address=0.0.0.0/0 dst-port=25 protocol=tcp in-interface={{ Interfacev4 }}
  when: checkSmtpV4 is failed
  register: SmtpIpv4
  
- name: Configurar bloqueio SMTP v6
  routeros_command:
    commands:
    - /ipv6 firewall filter add chain=forward action=drop src-address=::/0 dst-address=::/0 dst-port=25 protocol=tcp in-interface={{ Interfacev6 }}
  when: checkSmtpV6 is failed
  register: SmtpIpv6
  
- name: Verificar se MNDP está ativo
  routeros_command:
    commands:
    - /ip neighbor discovery-settings print
    wait_for: result[0] contains dynamic
  ignore_errors: yes
  register: checkMndp
  
 - name: Desabilitar MNDP
  routeros_command:
    commands:
    - /ip neighbor discovery-settings set discover-interface-list=none
  when: checkMndp is succeeded
  register: disableMndp 

- name: Verificar se filtro BOGONS v4 existe
  routeros_command:
    commands:
    - /ip firewall filter print
    wait_for: result[0] contains FILTRO-BOGONS-V4
  ignore_errors: yes
  register: CheckfiltroInterfaceV4
  
  - name: Verificar se filtro BOGONS v6 existe
  routeros_command:
    commands:
    - /ipv6 firewall filter print
    wait_for: result[0] contains FILTRO-BOGONS-V6
  ignore_errors: yes
  register: checkFiltroInterfaceV6
  
  - name: Configurar filtro BOGONS v4
  routeros_command:
    commands:
    - /ip firewall filter add action=drop chain=forward comment="Aplicando filtro de enderecos Bogons a interface" in-interface={{ Interfacev4 }} src-address-list=FILTRO-BOGONS-V4
  when: checkFiltroInterfaceV4 is failed
  register: fltroInterfaceV4
  
  - name: Configurar filtro BOGONS v6
  routeros_command:
    commands:
    - /ipv6 firewall filter add action=drop chain=forward in-interface={{ Interfacev6 }} src-address={{ PrefixoV6 }}
    - /ipv6 firewall filter chain=forward in-interface={{ Interfacev6 }} src-address-list=FILTRO-BOGONS-V4
  when: checkFiltroInterfaceV6 is failed
  register: filtroInterfaceV6
