---
- name: Verify if access-list de Filtro v4 exists
  routeros_command:
    commands:
      - /ip firewall address-list print
    wait_for: result[0] contains FILTRO-BOGONS-V4
  ignore_errors: yes
  register: checkFiltroBogonsv4

- name: Verify if access-list de Filtro v6 exists
  routeros_command:
    commands:
    - /ipv6 firewall address-list print 
    wait_for: result[0] contains FILTRO-BOGONS-V6
  ignore_errors: yes
  register: checkFiltroBogonsv6

- name: Create ACL BOGONS v4
  routeros_command:
    commands:
    - /ip firewall address-list add address=10.0.0.0/8 list=FILTRO-BOGONS-V4
    - /ip firewall address-list add address=100.64.0.0/10 list=FILTRO-BOGONS-V4
    - /ip firewall address-list add address=127.0.0.0/8 list=FILTRO-BOGONS-V4
    - /ip firewall address-list add address=169.254.0.0/16 list=FILTRO-BOGONS-V4
    - /ip firewall address-list add address=172.16.0.0/12 list=FILTRO-BOGONS-V4
    - /ip firewall address-list add address=192.0.0.0/24 list=FILTRO-BOGONS-V4
    - /ip firewall address-list add address=192.0.2.0/24 list=FILTRO-BOGONS-V4
    - /ip firewall address-list add address=192.168.0.0/24 list=FILTRO-BOGONS-V4
    - /ip firewall address-list add address=198.18.0.0/15 list=FILTRO-BOGONS-V4
    - /ip firewall address-list add address=198.51.100.0/24 list=FILTRO-BOGONS-V4
    - /ip firewall address-list add address=203.0.113.0/24 list=FILTRO-BOGONS-V4
    - /ip firewall address-list add address=224.0.0.0/3 list=FILTRO-BOGONS-V4
  when: checkFiltroBogonsv4 is failed
  register: filtroBogonsv4

- name: Create access list BOGONS v6
  routeros_command:
    commands:
    - /ipv6 firewall address-list add address=2000::/3 list=FILTRO-BOGONS-V6
    - /ipv6 firewall address-list add address=fe80::/64 list=FILTRO-BOGONS-V6
    - /ipv6 firewall address-list add address=::/128 list=FILTRO-BOGONS-V6
  when: checkFiltroBogonsv6 is failed
  register: filtroBogonsv6

- name: Verify if SMTP filter v4 exists
  routeros_command:
    commands:
    - /ip firewall filter print
    wait_for: result[0] contains dst-port=25
  ignore_errors: yes
  register: checkSmtpV4
  
- name: Verify if SMTP v6 exists
  routeros_command:
    commands:
    - /ipv6 firewall filter print
    wait_for: result[0] contains dst-port=25
  ignore_errors: yes
  register: checkSmtpV6

- name: Configure block port 25
  routeros_command:
    commands:
    - /ip firewall filter add chain=forward action=drop src-address=0.0.0.0/0 dst-address=0.0.0.0/0 dst-port=25 protocol=tcp in-interface={{ Interfacev4 }}
  when: checkSmtpV4 is failed
  register: SmtpIpv4
  
- name: Configure block port 25 v6
  routeros_command:
    commands:
    - /ipv6 firewall filter add chain=forward action=drop src-address=::/0 dst-address=::/0 dst-port=25 protocol=tcp in-interface={{ Interfacev6 }}
  when: checkSmtpV6 is failed
  register: SmtpIpv6
  
- name: Verify if MNDP is enabled
  routeros_command:
    commands:
    - /ip neighbor discovery-settings print
    wait_for: result[0] contains dynamic
  ignore_errors: yes
  register: checkMndp
  
- name: Disabled MNDP
  routeros_command:
    commands:
    - /ip neighbor discovery-settings set discover-interface-list=none
  when: checkMndp is succeeded
  register: disableMndp 

- name: Verify if BOGONS v4 exists
  routeros_command:
    commands:
    - /ip firewall filter print
    wait_for: result[0] contains FILTRO-BOGONS-V4
  ignore_errors: yes
  register: checkfiltroInterfaceV4
  
- name: Verify if BOGONS v6 exists
  routeros_command:
    commands:
    - /ipv6 firewall filter print
    wait_for: result[0] contains FILTRO-BOGONS-V6
  ignore_errors: yes
  register: checkFiltroInterfaceV6
  
- name: Configure BOGONS v4
  routeros_command:
    commands:
    - /ip firewall filter add action=drop chain=forward comment="Aplicando filtro de enderecos Bogons a interface" in-interface={{ Interfacev4 }} src-address-list=FILTRO-BOGONS-V4
  when: checkfiltroInterfaceV4 is failed
  register: filtroInterfaceV4
  
- name: Configure BOGONS v6
  routeros_command:
    commands:
    - /ipv6 firewall filter add action=drop chain=forward in-interface={{ Interfacev6 }} src-address={{ PrefixoV6 }}
    - /ipv6 firewall filter add chain=forward in-interface={{ Interfacev6 }} src-address-list=FILTRO-BOGONS-V6
  when: checkFiltroInterfaceV6 is failed
  register: filtroInterfaceV6

- name: Verify if RP Filter is enabled
  routeros_command:
    commands: 
    - /ip settings print
    wait_for: result[0] contains strict
  ignore_errors: yes
  register: checkRpfilter

- name: Enable RP Filter
  routeros_command:
    commands: 
    - /ip settings set rp-filter=strict
  when: checkRpfilter is failed
  register: rpfilterAtivado

