---
- name: Show version
  cisco.ios.ios_command:
    commands:
    - show version

- name: Checa se CEF está ativo
  cisco.ios.ios_command:
    commands:
    - show running-config | include cef
    wait_for: result[0] contains no
    retries: 2
  ignore_errors: yes
  register: checkCef
