---
- name: Checa se CEF está ativo
  cisco.ios.ios_command:
    commands:
    - show running-config | include cef
    wait_for: stdout contains no
    retries: 2
    ignore_errors: yes
  register: checkCef
